#-------------------------------
# General Site Settings
title: Amber's Blog
logo: # You can add own logo. For example '/images/logo.png'.
description: A compilation of ramblings with some coherent thoughts spliced in.
baseurl: "/blog" # The subpath of your site, e.g. /blog
url: "https://einsteinfrizz.github.io" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Amber Peek
  avatar: '/images/ambermini.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Amber's Blog
  description: A compilation of ramblings with some coherent thoughts spliced in.
  image: '/images/stockade-pano-success.jpg'


#-------------------------------
# Contact Settings
#contact:
#  email: your@email.com # Add your email for contant form
#  description: The Force is strong with this one. I have you now. I find your lack of faith disturbing. Hey, Luke! May the Force be with you. She must have hidden the plans in the escape pod. Send a detachment down to retrieve them, and see to it personally, Commander. There’ll be no one to stop us this time! # Add a description of your form

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
# social:

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
